apiVersion: v1
kind: Secret
metadata:
  name: nofux-klab
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/heimdallur/nofux-klab
  password: ${{ secrets.ARGOCD_KLAB }}
  username: argocd-klab
  project: argocd