apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana  
  project: grafana
  sources:
  - repoURL: https://github.com/heimdallur/nofux-klab
    targetRevision: HEAD
    path: platform/grafana
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 6.52.2
    helm:
      # valueFiles:
      #   - apps/dev-grafana/values.yaml
      values: |-
        service:
          type: LoadBalancer
          loadBalancerIP: "192.168.68.75"
          port: 8055
          targetPort: 3000
          annotations:
            metallb.universe.tf/address-pool: default
            metallb.universe.tf/allow-shared-ip: "grafana-shared"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true