apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  source:
    repoURL: https://github.com/heimdallur/nofux-klab
    targetRevision: main
    path: apps/dev-grafana/umbrella
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
