apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""            # match a PVC with no storageClassName
  volumeMode: Filesystem
  hostPath:
    path: /srv/grafana-data       # ensure this exists & is writable on every node
    type: Directory
  persistentVolumeReclaimPolicy: Delete