apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana  
  project: grafana
  sources:
  - repoURL: https://github.com/heimdallur/nofux-klab
    targetRevision: HEAD
    path: platform/grafana
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 6.52.2
    helm:
      values: |
        service:
          type: LoadBalancer
        persistence:
          enabled: true
          size: 5Gi
        adminUser: klab
        adminPassword: admin-password
        grafana.ini:
          server:
            http_port: 8055
            instance_name: "Klab Grafana"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true