apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 7.0.0
    helm:
      values:
        service:
          type: LoadBalancer
          loadBalancerIP: "192.168.68.75"
          port: 8055
          targetPort: 3000
          annotations:
            metallb.universe.tf/address-pool: default
            metallb.universe.tf/allow-shared-ip: "grafana-shared"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true