apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:            # or use NFS, AzureDisk, etc.
    path: /mnt/data/grafana
  persistentVolumeReclaimPolicy: Delete