persistence:
  enabled: true
  size: 5Gi
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce

adminUser: klab
adminPassword: strongpassword

service:
  type: LoadBalancer

grafana.ini:
  server:
    http_port: 8055
    instance_name: "Klab Grafana"
    