persistence:
  enabled: true
  size: 5Gi

adminUser: klab
adminPassword: strongpassword

service:
  type: LoadBalancer

grafana.ini:
  server:
    http_port: 8055
    instance_name: "Klab Grafana"
    