adminUser: klab
adminPassword: strongpassword

service:
  type: NodePort
  port: 8056
  targetPort: 3000
  nodePort: 32080

grafana.ini:
  server:
    http_port: 8055
    instance_name: "Klab Grafana"
    