adminUser: klab
adminPassword: strongpassword

service:
  type: LoadBalancer
  # bind to your single MetalLB IP
  loadBalancerIP: "192.168.1.100"
  port: 8055
  targetPort: 3000
  annotations:
    # select the pool
    metallb.universe.tf/address-pool: cheap
    # allow other services to use the same IP on other ports
    metallb.universe.tf/allow-shared-ip: "true"