persistence:
  enabled: true
  storageClassName: local-path
  size: 5Gi
  accessModes:
    - ReadWriteOnce

adminUser: klab
adminPassword: strongpassword

service:
  type: LoadBalancer

grafana.ini:
  server:
    http_port: 8055
    instance_name: "Klab Grafana"
    