apiVersion: v2
name: prometheus
description: Prometheus Umbrella Chart
type: application

version: 0.0.1
appVersion: "1.0"

dependencies:
- name: prometheus
  version: 27.12.1
  repository: https://prometheus-community.github.io/helm-charts