apiVersion: policy.k8s.io/v1
kind: PodSecurityException
metadata:
  name: allow-local-path-hostpath
  namespace: prometheus
spec:
  # Only allow Pods named helper-pod-create-* (the local-path helper pods)
  target:
    - group: ""           # core API
      version: "*"        # any version
      kind: Pod
      name: "helper-pod-create-*"
  # Elevate just those pods to privileged, so hostPath is allowed
  enforce: privileged
  audit:   privileged
  warn:    privileged