grafana:
  adminUser: klab
  adminPassword: strongpassword

  service:
    type: LoadBalancer
    name: http
    port: 8056
    targetPort: 8056
    loadBalancerIP: "192.168.68.75"
    annotations:
      metallb.universe.tf/address-pool: cheap
      metallb.universe.tf/allow-shared-ip: "true"

  image:
    repository: grafana/grafana
    tag: 9.0.0

  grafana.ini:
    server:
      http_port: 8056

  readinessProbe:
    httpGet:
      path: /api/health
      port: 8056
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

  livenessProbe:
    httpGet:
      path: /api/health
      port: 8056
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 6

  startupProbe:
    httpGet:
      path: /api/health
      port: 8056
    periodSeconds: 10
    failureThreshold: 30
