prometheus:
  server:
    service:
      type: LoadBalancer
      spec: 
        ports:
          - name: http
            nodePort: 32728
            port: 8056
            protocol: TCP
            targetPort: 9090
      loadBalancerIP: "192.168.68.75"
      annotations:
        metallb.universe.tf/address-pool:     cheap
        metallb.universe.tf/allow-shared-ip:  "true"

    persistentVolume:
      enabled: false

    image:
      repository: prometheus-community/prometheus
      tag:        "27.13.0"

  alertmanager:
    persistentVolume:
      enabled: false

