prometheus:
  server:
    service:
      type: LoadBalancer
      loadBalancerIP: "192.168.68.75"
      annotations:
        metallb.universe.tf/address-pool:     cheap
        metallb.universe.tf/allow-shared-ip:  "true"

      nodePort: 32728
      port: 8056

    persistentVolume:
      enabled: false


  image:
    repository: prom/prometheus
    tag: v27.12.1
    pullPolicy: IfNotPresent

  alertmanager:
    persistentVolume:
      enabled: false

