grafana:
  adminUser: klab
  adminPassword: strongpassword

  service:
    type: LoadBalancer
    name: http
    port: 8056
    targetPort: 8056
    loadBalancerIP: "192.168.68.75"
    annotations:
      metallb.universe.tf/address-pool: cheap
      metallb.universe.tf/allow-shared-ip: "true"

  server:
    persistentVolume:
      enabled: true
      size: 5Gi
      storageClassName: local-path
      accessModes:
        - ReadWriteOnce

  alertmanager:
    persistentVolume:
      enabled: true
      size: 2Gi
      storageClassName: local-path
      accessModes:
        - ReadWriteOnce

  image:
    repository: prometheus-community/prometheus
    tag: 27.13.0
