apiVersion: v2
name: grafana
description: Grafana Umbrella Chart
type: application

version: 0.0.1
appVersion: "1.0"

dependencies:
- name: grafana
  version: 8.15.0
  repository: https://grafana.github.io/helm-charts