grafana:
  adminUser: klab
  adminPassword: strongpassword

  service:
    type: LoadBalancer
    # bind to your single MetalLB IP
    loadBalancerIP: "192.168.68.75"
    annotations:
      # select the pool
      metallb.universe.tf/address-pool: cheap
      # allow other services to use the same IP on other ports
      metallb.universe.tf/allow-shared-ip: "true"
    ports:
      - name: service
        port: 8055
        targetPort: 8055

  grafana.ini:
    server:
      http_port: 8055