apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: grafana
  namespace: argocd
spec:
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc

  sourceRepos:
  - https://github.com/heimdallur/nofux-klab
  - https://grafana.github.io/helm-charts

  # Cluster-scoped resources Grafana will create
  clusterResourceWhitelist:
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: ""         # core API
    kind: Namespace

  # Namespaced resources Grafana will create
  namespaceResourceWhitelist:
  - group: ""         # core API
    kind: PersistentVolumeClaim
  - group: ""         
    kind: ServiceAccount
  - group: ""         
    kind: Secret
  - group: ""         
    kind: ConfigMap
  - group: ""         
    kind: Service
  - group: apps       # apps/v1
    kind: Deployment
  - group: rbac.authorization.k8s.io
    kind: Role
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
  - group: argoproj.io
    kind: Application
  - group: argoproj.io
    kind: AppProject
