apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: prometheus
  sources:
  - repoURL: https://github.com/heimdallur/nofux-klab/
    targetRevision: HEAD
    path: platform/prometheus
  - repoURL: https://prometheus-community.github.io/helm-charts/
    chart: prometheus
    targetRevision: 19.7.2
    helm:
      values: |
        server:
          service:
            type: LoadBalancer

  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true