apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: grafana
  spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: grafana
  source:
    path: platform/grafana/
    repoURL: https://github.com/heimdallur/nofux-klab
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true