apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: cheap
    metallb.universe.tf/allow-shared-ip: "true"
    metallb.io/ip-allocated-from-pool: cheap
  creationTimestamp: "2025-05-04T17:01:46Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
  namespace: argocd
  resourceVersion: "688689"
  uid: 5db08d9c-70e7-49b5-beff-b95eed404056
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.111.5.11
  clusterIPs:
  - 10.111.5.11
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31201
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 32306
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.68.75
      ipMode: VIP