apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: grafana
  source:
    path: platform/argocd/
    repoURL: https://github.com/heimdallur/nofux-klab
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true