pihole:
  service:
    type: LoadBalancer
    loadBalancerIP: "192.168.68.75"
    ports:
      http: 8081
    annotations:
      metallb.universe.tf/address-pool: cheap
      metallb.universe.tf/allow-shared-ip: "true"
  
  persistence:
    enabled: false
  
  # containerPorts:
  #   http: 8081

  image:
    repository: savepointsam/pihole
    tag: 0.2.0

  pihole:
    timezone: "Europe/London"
    virtualHost: 8081

    readinessProbe:
      enabled: false
    #   httpGet:
    #     path: /api/health
    #     port: 8081
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    #   timeoutSeconds: 5
    #   failureThreshold: 6

    livenessProbe:
      enabled: false
    #   httpGet:
    #     path: /api/health
    #     port: 8081
    #   initialDelaySeconds: 60
    #   periodSeconds: 30
    #   timeoutSeconds: 5
    #   failureThreshold: 6

    startupProbe:
      enabled: false
    #   httpGet:
    #     path: /api/health
    #     port: 8081
    #   periodSeconds: 10
    #   failureThreshold: 30
