apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prometheus
  namespace: argocd
spec:
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/heimdallur/nofux-klab.git
  - https://prometheus-community.github.io/helm-charts


  clusterResourceWhitelist:
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: ""
    kind: Namespace

namespaceResourceWhitelist:
  - group: ""
    kind: PersistentVolumeClaim
  - group: ""
    kind: ServiceAccount
  - group: ""
    kind: Secret
  - group: ""
    kind: ConfigMap
  - group: ""
    kind: Service
  - group: apps
    kind: Deployment
  - group: apps
    kind: StatefulSet      # ← must be here
  - group: apps
    kind: DaemonSet        # ← must be here
  - group: rbac.authorization.k8s.io
    kind: Role
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
  - group: argoproj.io
    kind: Application
  - group: argoproj.io
    kind: AppProject
