apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus

  source:
    repoURL: https://github.com/heimdallur/nofux-klab
    targetRevision: main
    path: apps/prometheus/umbrella

    helm:
      dependencyUpdate: true
      valueFiles:
        - values.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true