apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeMode: Filesystem
  hostPath:
    path: /var/lib/prometheus-data
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete