apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2025-05-11T13:43:44Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: alertmanager
  name: storage-prometheus-alertmanager-0
  namespace: prometheus
  resourceVersion: "931961"
  uid: cd154f03-48b0-47dd-8b56-a6467c9cd0dd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem