apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pihole
  namespace: argocd
spec:
  description: Pi-Hole DNS for Home Lab
  destinations:
    - name: in-cluster
      namespace: 'pihole'
      server: https://kubernetes.default.svc
    - name: in-cluster
      namespace: 'argocd'
      server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/heimdallur/nofux-klab.git
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
